# Generated by Django 5.1.1 on 2024-09-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
