# Generated by Django 5.1.1 on 2024-09-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_signature_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
