# Generated by Django 5.1.1 on 2024-09-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_signature_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='address',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='website',
        ),
        migrations.AddField(
            model_name='signature',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='signature',
            name='function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='signature_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
