# Generated by Django 5.1.1 on 2024-09-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_rename_phone_number_signature_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
