# Generated by Django 5.1.1 on 2024-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0007_alter_signature_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
