# Generated by Django 5.1.1 on 2024-09-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0009_banner_alter_signature_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
    ]
