# Generated by Django 5.1.1 on 2024-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_remove_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
