# Generated by Django 5.1.1 on 2024-09-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0011_alter_signature_mobile_alter_signature_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
